/**
 * @module controllers/adminaid
 * @author jesse reichler <mouser@donationcoder.com>
 * @copyright 5/1/19
 * @description
 * This module defines the AdminAid class, which provides support for backend administration activities
 */

"use strict";


// requirement service locator
const jrequire = require("../helpers/jrequire");

// our helper modules
const jrhMisc = require("../helpers/jrh_misc");
const JrResult = require("../helpers/jrresult");

// models
const AppModel = jrequire("models/app");
const RoomModel = jrequire("models/room");









/**
 * Provides support for backend administrative activities
 *
 * @class AdminAid
 */
class AdminAid {

	//---------------------------------------------------------------------------
	// constructor
	constructor() {
	}
	//---------------------------------------------------------------------------


	//---------------------------------------------------------------------------
	async addTestAppsAndRooms(req, addCountApps, addCountRooms) {
		// add some test apps and rooms
		var successMessage1, successMessage2;
		var app, room;
		var appindexString, roomindexString;
		var appid;
		var appindexStart = 1;
		var roomindexStart = 1;
		var appsAdded = 0;
		var roomsAdded = 0;
		var shortcode;
		const maxTrysPerClash = 1000;
		var foundone;
		var clashTryCount;

		for (var appindex = 0; appindex < addCountApps; appindex += 1) {

			// create an app
			clashTryCount = 0;
			do {
				appindexString = (appindexStart + appsAdded).toString();
				shortcode = "A" + appindexString;
				foundone = await AppModel.findOneByShortcode(shortcode);
				++clashTryCount;
				++appindexStart;
			} while (foundone && clashTryCount <= maxTrysPerClash);
			if (clashTryCount > maxTrysPerClash) {
				// return false;
				break;
			}

			app = AppModel.createModel({
				shortcode,
				name: "App" + appindexString,
				label: "Application # " + appindexString,
				description: "Test App generated by administration backend on " + jrhMisc.getNiceNowString(),
			});

			// save it
			await app.dbSave();
			appsAdded += 1;
			appid = app.getId();

			// now create some rooms attached to the app
			for (var roomindex = 0; roomindex < addCountRooms; roomindex += 1) {

				clashTryCount = 0;
				do {
					roomindexString = (roomindexStart + roomsAdded).toString();
					shortcode = "R" + roomindexString + "A" + appindexString;
					foundone = await RoomModel.findOneByShortcode(shortcode);
					++clashTryCount;
					++roomindexStart;
				} while (foundone && clashTryCount <= maxTrysPerClash);
				if (clashTryCount > maxTrysPerClash) {
					// return false;
					break;
				}

				room = RoomModel.createModel({
					appid,
					shortcode,
					name: "Room" + roomindexString + "A" + appindexString,
					label: "Room # " + roomindexString + " for App # " + appindexString,
					description: "Test Room generated by administration backend on " + jrhMisc.getNiceNowString() + " for App " + appindexString,
				});

				// save it
				await room.dbSave();
				roomsAdded += 1;
			}
		}

		successMessage1 = "Created " + appsAdded.toString() + " Apps.";
		successMessage2 = "Created " + roomsAdded.toString() + " Rooms.";

		// success
		// push message on session
		var jrResult = JrResult.makeSuccess(successMessage1);
		jrResult.pushSuccess(successMessage2);
		jrResult.addToSession(req);
		// return success
		return true;
	}
	//---------------------------------------------------------------------------


}







// export the class as the sole export
module.exports = new AdminAid();
